const images=[

// Series-peliculas-tv


{id:'2',imageName:'./Series - peliculas - tv/krustyboca.jfif',tag:'de series / peliculas / tv'},
{id:'3',imageName:'./Series - peliculas - tv/toystoryboca.jfif', tag:'de series / peliculas / tv'},
{id:'4',imageName:'./Series - peliculas - tv/toystoryboca2.jfif',tag:'de series / peliculas / tv'},
{id:'5',imageName:'./Series - peliculas - tv/yodaboca.jfif',tag:'de series / peliculas / tv'},
{id:'7',imageName:'./Series - peliculas - tv/abuelosimpsongritaboca.jfif',tag:'de series / peliculas / tv'},
{id:'12',imageName:'./Series - peliculas - tv/aquiesdondevengoaimaginarmerefuerzos.jfif',tag:'de series / peliculas / tv'},
{id:'14',imageName:'./Series - peliculas - tv/baiabaia1.jfif',tag:'de series / peliculas / tv'},
{id:'15',imageName:'./Series - peliculas - tv/baiabaia2.jfif',tag:'de series / peliculas / tv'},
{id:'17',imageName:'./Series - peliculas - tv/barneyinyecteloenmisvenas.jfif',tag:'de series / peliculas / tv'},
{id:'19',imageName:'./Series - peliculas - tv/bokemon.jfif', tag:'de series / peliculas / tv'},
{id:'23',imageName:'./Series - peliculas - tv/bugsbunnyboca.jfif',tag:'de series / peliculas / tv'},
{id:'24',imageName:'./Series - peliculas - tv/burnsboca.jfif',tag:'de series / peliculas / tv'},
{id:'25',imageName:'./Series - peliculas - tv/burnsboca2.jfif',tag:'de series / peliculas / tv'},
{id:'32',imageName:'./Series - peliculas - tv/dexterboca.jfif',tag:'de series / peliculas / tv'},
{id:'33',imageName:'./Series - peliculas - tv/rickymortybostero.jfif',tag:'de series / peliculas / tv'},
{id:'34',imageName:'./Series - peliculas - tv/rickymortybostero2.jfif',tag:'de series / peliculas / tv'},
{id:'35',imageName:'./Series - peliculas - tv/rickymortybostero3.jfif', tag:'de series / peliculas / tv'},
{id:'36',imageName:'./Series - peliculas - tv/rickymortybostero4.jfif',tag:'de series / peliculas / tv'},
{id:'43',imageName:'./Series - peliculas - tv/skinnerboca.jfif',tag:'de series / peliculas / tv'},
{id:'45',imageName:'./Series - peliculas - tv/supercampeonessteveboca.jfif',tag:'de series / peliculas / tv'},
{id:'58',imageName:'./Series - peliculas - tv/elresplandormc1.jfif',tag:'de series / peliculas / tv'},
{id:'59',imageName:'./Series - peliculas - tv/elresplandormc2.jfif',tag:'de series / peliculas / tv'},
{id:'65',imageName:'./Series - peliculas - tv/friendsthebigbangtheorypiluso.jfif',tag:'de series / peliculas / tv'},
{id:'67',imageName:'./Series - peliculas - tv/gameofthronesboca.jfif',tag:'de series / peliculas / tv'},
{id:'74',imageName:'./Series - peliculas - tv/hemanboca2.jfif',tag:'de series / peliculas / tv'},
{id:'75',imageName:'./Series - peliculas - tv/hemanboca3.jfif',tag:'de series / peliculas / tv'},
{id:'76',imageName:'./Series - peliculas - tv/hemanescudoboca.jfif',tag:'de series / peliculas / tv'},
{id:'77',imageName:'./Series - peliculas - tv/herculesboca.jfif',tag:'de series / peliculas / tv'},
{id:'79',imageName:'./Series - peliculas - tv/holamiguelboca.jfif',tag:'de series / peliculas / tv'},
{id:'80',imageName:'./Series - peliculas - tv/homeroboca.jfif',tag:'de series / peliculas / tv'},
{id:'87',imageName:'./Series - peliculas - tv/jessepinkmanboca.jfif',tag:'de series / peliculas / tv'},
{id:'94',imageName:'./Series - peliculas - tv/lossimpsonboca.jfif',tag:'de series / peliculas / tv'},
{id:'95',imageName:'./Series - peliculas - tv/majinboodalebo.jfif',tag:'de series / peliculas / tv'},
{id:'101',imageName:'./Series - peliculas - tv/mrspockbostero.jfif',tag:'de series / peliculas / tv'},
{id:'102',imageName:'./Series - peliculas - tv/nelsonboca.jfif',tag:'de series / peliculas / tv'},
{id:'110',imageName:'./Series - peliculas - tv/obandoup.jfif',tag:'de series / peliculas / tv'},
{id:'139',imageName:'./Series - peliculas - tv/volveralfuturoboca.jfif',tag:'de series / peliculas / tv'},
{id:'142',imageName:'./Series - peliculas - tv/okupasboca.jpg',tag:'de series / peliculas / tv'},


// De otros memes


{id:'1',imageName:'./de otros memes/alejatedemispibesdescendido.jfif',tag:'de otros memes'},
{id:'6',imageName:'./de otros memes/wtfboca.jfif',tag:'de otros memes'},
{id:'8',imageName:'./de otros memes/acasoyotepediboca.jfif',tag:'de otros memes'},
{id:'9',imageName:'./de otros memes/agarramequelomatoboca.jfif',tag:'de otros memes'},
{id:'10',imageName:'./de otros memes/analisisclinicobocardium.jfif',tag:'de otros memes'},
{id:'11',imageName:'./de otros memes/apuntodeexplotarboca.jfif',tag:'de otros memes'},
{id:'13',imageName:'./de otros memes/austedesletraenrefuerzosboca.jfif',tag:'de otros memes'},
{id:'16',imageName:'./de otros memes/barfumandoborrachollorandocantordefondo.jfif',tag:'de otros memes'},
{id:'18',imageName:'./de otros memes/bocamusicstops.jfif',tag:'de otros memes'},
{id:'20',imageName:'./de otros memes/botondalebo1.jfif',tag:'de otros memes'},
{id:'21',imageName:'./de otros memes/botondalebo2.jfif',tag:'de otros memes'},
{id:'22',imageName:'./de otros memes/bradpittboca.jfif',tag:'de otros memes'},
{id:'31',imageName:'./de otros memes/cosaconbinocularesysupeneconbinocularesmiraninteresadoselmonitor.jfif',tag:'de otros memes'},
{id:'39',imageName:'./de otros memes/sisosantibocadeciloahora.jfif',tag:'de otros memes'},
{id:'40',imageName:'./de otros memes/sisosderiberdeciloahora.jfif',tag:'de otros memes'},
{id:'41',imageName:'./de otros memes/sisosgashinadeciloahora.jfif',tag:'de otros memes'},
{id:'42',imageName:'./de otros memes/sitefuistealabdeciloahora.jfif',tag:'de otros memes'},
{id:'44',imageName:'./de otros memes/stonksboca.jfif',tag:'de otros memes'},
{id:'48',imageName:'./de otros memes/temiroteobservoteanalizoyterespetoboca.jfif',tag:'de otros memes'},
{id:'62',imageName:'./de otros memes/esemalditohijodeperralologroboca.jfif',tag:'de otros memes'},
{id:'66',imageName:'./de otros memes/fuckingbrasilerosmotherfuckersbradpittboca.jfif',tag:'de otros memes'},
{id:'69',imageName:'./de otros memes/groneagachadaintentandoentenderquediceotroboca.jfif',tag:'de otros memes'},
{id:'70',imageName:'./de otros memes/groneatrasdearbolrelamiendofrotandomanos.jfif',tag:'de otros memes'},
{id:'71',imageName:'./de otros memes/gronecantandoemocionadoboca.jfif',tag:'de otros memes'},
{id:'72',imageName:'./de otros memes/gronedandosecuentadealgoboca.jfif',tag:'de otros memes'},
{id:'83',imageName:'./de otros memes/igdelaparceraboca.jfif',tag:'de otros memes'},
{id:'85',imageName:'./de otros memes/intentacontrolarmanoboca.jfif',tag:'de otros memes'},
{id:'86',imageName:'./de otros memes/jerryboca.jfif',tag:'de otros memes'},
{id:'96',imageName:'./de otros memes/maravillosajugada.jfif',tag:'de otros memes'},
{id:'98',imageName:'./de otros memes/minarubiaascoperolorepiensa1.jfif', tag:'de otros memes'},
{id:'99',imageName:'./de otros memes/minarubiaascoperolorepiensa2.jfif',tag:'de otros memes'},
{id:'103',imageName:'./de otros memes/nenallorandotratandodeexplicarymadreyasabiendoqueselamando.jfif',tag:'de otros memes'},
{id:'104',imageName:'./de otros memes/nenarubiadibujandofrustradaporboca.jfif',tag:'de otros memes'},
{id:'105',imageName:'./de otros memes/nenefamosogavinboca.jfif',tag:'de otros memes'},
{id:'106',imageName:'./de otros memes/nenegronemirandodereojohaciendoseelboludo.jfif',tag:'de otros memes'},
{id:'108',imageName:'./de otros memes/noloserickbocaparecedelab.jfif',tag:'de otros memes'},
{id:'111',imageName:'./de otros memes/pachabocaunapinturita.jfif',tag:'de otros memes'},
{id:'114',imageName:'./de otros memes/peluchemonobocahaciendoseelboludo.jfif',tag:'de otros memes'},
{id:'127',imageName:'./de otros memes/pulgararribapibeboca.jfif',tag:'de otros memes'},
{id:'128',imageName:'./de otros memes/puñoapretadoboca.jfif',tag:'de otros memes'},
{id:'129',imageName:'./de otros memes/ranapelucheacostadacorazones.jfif',tag:'de otros memes'},
{id:'130',imageName:'./de otros memes/ranapeluchecorazones.jfif',tag:'de otros memes'},
{id:'131',imageName:'./de otros memes/rataazulsaliendoporunapuertaboca.jfif',tag:'de otros memes'},
{id:'138',imageName:'./de otros memes/viejasecaeensupiezaboca.jfif',tag:'de otros memes'},
{id:'140',imageName:'./de otros memes/zorrodibujitopiluso.jfif',tag:'de otros memes'},
{id:'164',imageName:'./de otros memes/neneconunarmallorando.jpg',tag:'de otros memes'},


// Simios


{id:'38',imageName:'./Simios/simiogritaboke.jpg',tag:'simios'},
{id:'100',imageName:'./simios/monogolpeagritaboca.jpg',tag:'simios'},
{id:'165',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'166',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'167',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'168',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'169',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'170',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'171',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'172',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'173',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'174',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'175',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'176',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},
// {id:'177',imageName:'./simios/simioqueriendolalibertadores.jpg',tag:'simios'},



// Hoy juega boca (pure boke)


{id:'78',imageName:'./Hoy juega boca - pure boke/hinchatrabadoenlabombonera.jfif',tag:'Hoy juega boca (pure boke)'},
{id:'81',imageName:'./Hoy juega boca - pure boke/hoyjuegaboca1.jfif', tag:'hoy juega boca (pure boke)'},
{id:'82',imageName:'./Hoy juega boca - pure boke/hoyjuegaboca2.jfif',tag:'hoy juega boca (pure boke)'},
{id:'84',imageName:'./Hoy juega boca - pure boke/indiosolariboca.jfif',tag:'hoy juega boca (pure boke)'},
// {id:'150',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'151',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'152',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'153',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'154',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'155',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'156',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'157',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'158',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'159',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'160',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'161',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'162',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},
// {id:'163',imageName:'./Hoy juega boca pure boke/',tag:'hoy juega boca (pure boke)'},


// Otros


{id:'93',imageName:'./otros/losientodescendernoestaenmidiccionario.jfif',tag:'otros'},
{id:'97',imageName:'./otros/miketysonboca.jfif',tag:'otros'},
{id:'135',imageName:'./otros/unpocoma.jfif',tag:'otros'},
{id:'136',imageName:'./otros/verificacionequiposquedescendieron1.jfif',tag:'otros'},
{id:'137',imageName:'./otros/verificacionequiposquedescendieron2.jfif',tag:'otros'},
{id:'107',imageName:'./otros/nenerezandobombonera.jfif',tag:'otros'},
{id:'109',imageName:'./otros/nubebostera.jfif',tag:'otros'},
{id:'112',imageName:'./otros/pastillasirsealabquedarseenprimera.jfif',tag:'otros'},
{id:'113',imageName:'./otros/peladoredurobailandoboca.jfif',tag:'otros'},
{id:'115',imageName:'./otros/pikachuboca.jfif',tag:'otros'},
{id:'116',imageName:'./otros/pikachuboca2.jfif',tag:'otros'},
{id:'117',imageName:'./otros/pinguinoarcoflechapilusocorazones.jfif',tag:'otros'},
{id:'118',imageName:'./otros/pinguinoboca.jfif',tag:'otros'},
{id:'119',imageName:'./otros/pinguinoboca2.jfif',tag:'otros'},
{id:'120',imageName:'./otros/pinguinoboca3.jfif',tag:'otros'},
{id:'121',imageName:'./otros/pinguinoboca4.jfif',tag:'otros'},
{id:'122',imageName:'./otros/pinguinoboca5.jfif',tag:'otros'},
{id:'123',imageName:'./otros/pinguinoboca6.jfif',tag:'otros'},
{id:'124',imageName:'./otros/pinguinoboca7.jfif',tag:'otros'},
{id:'125',imageName:'./otros/pinguinoboca8.jfif',tag:'otros'},
{id:'26',imageName:'./otros/caballocamisetaboca.jfif',tag:'otros'},
{id:'27',imageName:'./otros/chanchonodesciende.jfif',tag:'otros'},
{id:'29',imageName:'./Otros/conejomirandorelojdibujitoboca.jfif',tag:'otros'},
{id:'37',imageName:'./otros/russonator.jfif',tag:'otros'},
{id:'46',imageName:'./otros/takahara.jfif',tag:'otros'},
{id:'47',imageName:'./otros/tecladoboca.jfif',tag:'otros'},
{id:'49',imageName:'./Otros/tomcruiseboca.jfif',tag:'otros'},
{id:'50',imageName:'./Otros/dimitriboca.jfif',tag:'otros'},
{id:'53',imageName:'./otros/distanciasocialboca1.jfif',tag:'otros'},
{id:'54',imageName:'./otros/distanciasocialboca2.jfif',tag:'otros'},
{id:'55',imageName:'./otros/distanciasocialboca3.jfif',tag:'otros'},
{id:'56',imageName:'./otros/distanciasocialboca4.jfif',tag:'otros'},
{id:'57',imageName:'./Otros/elneneestabienboca.jfif',tag:'otros'},
{id:'60',imageName:'./otros/eminemboca.jfif',tag:'otros'},
{id:'61',imageName:'./otros/emojiboca.jfif',tag:'otros'},
{id:'63',imageName:'./otros/finallybocardium.jfif',tag:'otros'},
{id:'64',imageName:'./otros/focaboca.jfif',tag:'otros'},
{id:'68',imageName:'./otros/gordosubtetelefonogroneboca.jfif',tag:'otros'},
{id:'73',imageName:'./Otros/gronepeliculagorritoboca.jfif',tag:'otros'},


// Boke religioso / Artistico


{id:'147',imageName:'./Boke religioso - artistico/religionboca.jfif',tag:'boke religioso / artístico'},
{id:'148',imageName:'./Boke religioso - artistico/religionboca2.jfif',tag:'boke religioso / artístico'},
{id:'149',imageName:'./Boke religioso - artistico/religionboca3.jfif',tag:'boke religioso / artístico'},
{id:'28',imageName:'./Boke religioso - artistico/cielobosterobanderabudgeboulognedelviso.jfif',tag:'boke religioso / artístico'},
{id:'30',imageName:'./Boke religioso - artistico/consejodefutbolantiguagrecia.jfif',tag:'boke religioso / artístico'},
{id:'51',imageName:'./Boke religioso - artistico/diosconplacaestoesboca.jfif',tag:'boke religioso / artístico'},
{id:'52',imageName:'./Boke religioso - artistico/disculpeestoesboca1.jfif', tag:'boke religioso / artístico'},
{id:'88',imageName:'./Boke religioso - artistico/joinreligionboca.jfif',tag:'boke religioso / artístico'},
{id:'89',imageName:'./Boke religioso - artistico/juliocesarbostero1.jfif',tag:'boke religioso / artístico'},
{id:'90',imageName:'./Boke religioso - artistico/juliocesarbostero2.jfif',tag:'boke religioso / artístico'},
{id:'91',imageName:'./Boke religioso - artistico/juliocesarbostero3.jfif',tag:'boke religioso / artístico'},
{id:'92',imageName:'./Boke religioso - artistico/juliocesarbostero4.jfif',tag:'boke religioso / artístico'},
{id:'126',imageName:'./Boke religioso - artistico/pinturaantiguavariostiposincredulosboca.jfif',tag:'boke religioso / artístico'},





    ];

    export default images